@baseUrl =http://localhost:3001
@authorization = Bearer {{login.response.body.token}}

///////////////USERS ENDPOINTS/////////////////
### REGISTER
# @name register
POST {{baseUrl}}/auth/register
Accept: application/json
Content-Type: application/json

{
    "userName": "RodXIII",
    "email": "rodri@badass.cool",
    "address":"calle de la gominola, escalera piruleta",
    "password": "123456Az",
    "country": "Spain",
    "creditcardNumber":111111111111111111111,
    "creditcardType":"gastamas",
    "RoleId":1
}



### LOGIN
# @name login
POST {{baseUrl}}/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "rodri@badass.cool",
    "password": "123456Az"
}


### LOGOUT
GET {{baseUrl}}/auth/logout
Accept: application/json
Authorization: {{authorization}}



### PROFILE
GET {{baseUrl}}/auth/152
Accept: application/json
Authorization: {{authorization}}





////////////////////PRODUCTS//////////////////
### GET ALL
GET {{baseUrl}}/product/allProduct



### PRODUCT BY ID
GET {{baseUrl}}/product/id/355
Content-Type: application/json



### CATEGORY
GET {{baseUrl}}/product/cat/drums
Content-Type: application/json



### BRAND
GET {{baseUrl}}/product/br/fender
Content-Type: application/json



### SEARCH
GET {{baseUrl}}/product/search/michael
Content-Type: application/json























/////////////INVOICES////////////////////
###

GET {{baseUrl}}/inv/invoices
Content-Type: application/json


###

GET {{baseUrl}}/inv/invoice-id
Content-Type: application/json

{
    "id": 1
}



###

GET {{baseUrl}}/inv/invoice-user
Content-Type: application/json

{
    "UserId": 152
}


###

GET {{baseUrl}}/inv/invoice-product
Content-Type: application/json

{
    "ProductId": 666
}
